site_name: Invidious Documentation
site_url: https://docs.invidious.io/
repo_url: https://github.com/iv-org/documentation
site_author: The Invidious project.
site_description: >-
  The official Invidious documentation
copyright: CC0 1.0 Universal (CC0 1.0)

nav:
  - Home: 'index.md'
  - 'General':
    - 'instances.md'
    - 'export-youtube-subscriptions.md'
    - 'preferences.md'
    - 'applications.md'
    - 'search-filters.md'
    - 'url-parameters.md'
    - 'proxy-videos.md'
    - 'geoblocking.md'
    - 'umatrix.md'
    - 'known-exception.md'
    - 'faq.md'
  - 'For Administrators':
    - 'installation.md'
    - 'configuration.md'
    - 'apache2.md'
    - 'nginx.md'
    - 'caddy.md'
    - 'db-maintenance.md'
    - 'captcha-bug.md'
    - 'anti-captcha.md'
    - 'takedown.md'
    - 'hide-instance-behind-proxy-server.md'
    - 'reset-pass.md'
  - 'For Developers':
    - 'api.md'
    - 'api/common_types.md'
    - 'api/channels_endpoint.md'
    - 'api/authenticated-endpoints.md'

theme:
  name: material
  font: false
  palette:
    primary: black
  logo: images/invidious.png # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo
  favicon: images/favicon.ico # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#favicon
  features:
    - navigation.tracking # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking
    - navigation.expand # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.top # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - content.code.copy # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iv-org/documentation

markdown_extensions:
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details # https://facelessuser.github.io/pymdown-extensions/extensions/details/
